name: Deploy Infrastructure

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  AWS_REGION: ap-northeast-1
  NODE_VERSION: '20'

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: infrastructure/package-lock.json

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install dependencies
        run: |
          cd infrastructure
          npm ci

      - name: Build TypeScript
        run: |
          cd infrastructure
          npm run build

      - name: Run CDK Synth
        run: |
          cd infrastructure
          npx cdk synth

      - name: Deploy to AWS (main branch only)
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          cd infrastructure
          npx cdk deploy --all --require-approval never

      - name: Show stack outputs
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          aws cloudformation describe-stacks \
            --stack-name VtsInfrastructureStack \
            --query 'Stacks[0].Outputs' \
            --output table
